name: Java CI with Maven

on:
  push:
    branches: [ b1 ]
  pull_request:
    branches: [ b1 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    #- uses: actions/checkout@v2
    #- name: Set up JDK 11
    #  uses: actions/setup-java@v2
    #  with:
    #    java-version: '11'
    #    distribution: 'adopt'
    #    cache: maven
    #- name: Resolve Dependencies
    #  run: mvn dependency:analyze
    #- name: Analyze Dependencies
    #  run: mvn dependency:analyze
    #- name: Build with Maven
    #  run: mvn -B package --file pom.xml
    #- name: Tests
    #  run: mvn test
    - name: Hello
      run: echo "Hello World"
