name: New candidate version

on:
  push:
    branches:
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    
    - name: Resolve Dependencies
      run: mvn dependency:analyze
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Tests
      run: mvn test

  sonarqube:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: SonarCube analysis
      run: mvn clean verify sonar:sonar -Dsonar.host.url=${SONAR_HOST_URL} -Dsonar.projectKey=${SONAR_TOKEN}

  publish:
    needs: sonarqube    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        image: franklinmatheus/training
        registry: docker.io
        tags: latest-release
    
    #steps:
    #- uses: actions/checkout@v2    
    #- name: Release Branch Name
    #  id: vars
    #  run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

    #- uses: mukunku/tag-exists-action@v1.0.0
    #  id: tagExists
    #  with: 
    #    tag: ${{ steps.vars.outputs.short_ref }}
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    #- name: Bump version and push tag
    #  if: ${{ steps.tagExists.outputs.exists }} == 'False'
    #  id: tag_version
    #  uses: mathieudutour/github-tag-action@v5.6
    #  with:
    #    github_token: ${{ secrets.ACCESS_TOKEN }}
    #    release_branches: release/*

    #- name: Create a GitHub release
    #  if: ${{ steps.tagExists.outputs.exists }} == 'False'
    #  uses: actions/create-release@v1
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    #  with:
    #    tag_name: ${{ steps.tag_version.outputs.new_tag }}
    #    release_name: Release ${{ steps.tag_version.outputs.new_tag }}
    #    body: ${{ steps.tag_version.outputs.changelog }}

    