name: New candidate version

on:
  release:
    types: [created,published]

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Resolve Dependencies
      run: mvn dependency:analyze
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Tests
      run: mvn test
    - name: Create release
      run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' . ./release
    - name: Create tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Version
    run: echo ${{ github.event.release.tag_name }}