name: New candidate version

on:
  push:
    branches:
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Resolve Dependencies
      run: mvn dependency:analyze
    #- name: Build with Maven
    #  run: mvn -B package --file pom.xml
    #- name: Tests
    #  run: mvn test

  publish:
    needs: build    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Release Branch Name
      id: vars
      run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: franklinmatheus/training	
        tags: release, latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}    
    
    #steps:
    #- uses: actions/checkout@v2    
    #- name: Release Branch Name
    #  id: vars
    #  run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

    #- uses: mukunku/tag-exists-action@v1.0.0
    #  id: tagExists
    #  with: 
    #    tag: ${{ steps.vars.outputs.short_ref }}
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    #- name: Bump version and push tag
    #  if: ${{ steps.tagExists.outputs.exists }} == 'False'
    #  id: tag_version
    #  uses: mathieudutour/github-tag-action@v5.6
    #  with:
    #    github_token: ${{ secrets.ACCESS_TOKEN }}
    #    release_branches: release/*

    #- name: Create a GitHub release
    #  if: ${{ steps.tagExists.outputs.exists }} == 'False'
    #  uses: actions/create-release@v1
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    #  with:
    #    tag_name: ${{ steps.tag_version.outputs.new_tag }}
    #    release_name: Release ${{ steps.tag_version.outputs.new_tag }}
    #    body: ${{ steps.tag_version.outputs.changelog }}

    