name: New candidate version

on:
  push:
    branches:
      - 'release/**'

# change

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Resolve Dependencies
      run: mvn dependency:analyze
    #- name: Build with Maven
    #  run: mvn -B package --file pom.xml
    #- name: Tests
    #  run: mvn test

  publish:
    needs: build    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Create release
      run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' . ./release
    - name: Create tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        RELEASE_BRANCHES: release/*