name: New candidate version

on:
  push:
    branches:
      - 'release/**'

# change

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Resolve Dependencies
      run: mvn dependency:analyze
    #- name: Build with Maven
    #  run: mvn -B package --file pom.xml
    #- name: Tests
    #  run: mvn test

  publish:
    needs: build    
    runs-on: ubuntu-latest
    
    steps:
    - name: Release Branch Name
      id: vars
      run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*}
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: franklinmatheus/training	
        tags: ${{ steps.vars.outputs.short_ref }}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      